### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by fizzvr** [edwinspire/usaga#1]
@edwinspire como lo hago funcionar? mofifica el readme tambien sry

**Comment by edwinspire** [comment]
Hay que bajarse todo el proyecto como zip, tambien se deben bajar las librerias y copiarlas junto donde se encuentra el ejecutable opensaga.

**Comment by edwinspire** [comment]
Se hará los cambios para mostrar las instrucciones detalladas de instalacion.
