### ISSUE TITLE
Al apretar el botón Guardar en Abonado/Principal sale un alert "TypeError: Cannot call method 'getElementsByTagName' of null"

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#11]
Luego de crear un abonado con el botón nuevo, al querer guardar los cambios con el botón Guardar, sale el alert con el mensaje "TypeError: Cannot call method 'getElementsByTagName' of null"

**Comment by edwinspire** [comment]
No se presenta ese bug en mi copia. Actualizar los archivos y probar

**Comment by Nnino** [comment]
Me da la impresión que es por la base de datos. En este momento la mia se encuentra vacía. Probaré con una con datos.

**Comment by Nnino** [comment]
Actualicé todos los archivos, probé con una base de datos llena y el error aún persiste.

**Comment by edwinspire** [comment]
El archivo que controla eso es opensaga_account.js. Revisar la funcion SaveAccount()
Recordar q hubo cambios en la base de datos y en el ejecutable opensaga.

**Comment by edwinspire** [comment]
Revisar los commits del dia 18 de enero

https://github.com/edwinspire/opensaga/commits/master

**Comment by Nnino** [comment]
Solucionado, el problema estaba en el ejecutable OpenSAGA
