### ISSUE TITLE
La fecha de nacimiento en uSMS/Contactos no es capturada correctamente

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#12]
Al tratar de modificar la fecha de nacimiento de un contacto, la fecha que efectivamente se almacena es un día anterior al ingresado realmente.

**Comment by edwinspire** [comment]
Revisando....
La fecha se guarda correctamente en la base de datos, la base de datos envia la fecha corrrecta al datetexbox, al crear el objeto Date de javascript es donde por alguna razon le resta un dia menos. Sigo investigando.

**Comment by edwinspire** [comment]
Solucionado.
