### ISSUE TITLE
Duda respecto al campo provider en "Sistema/Abonado/Usuario/Control de Alarma"

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#13]
Por qué el nombre del proveedor se encuentra dentro de un select y no como un campo normal?...

**Comment by Nnino** [comment]
Y lo otro, en que parte se pueden agregar los proveedores para que se muestren en los select respectivos?, porque yo intenté agregarlos manualmente pero no se mostraban.

**Comment by edwinspire** [comment]
Los proveedores (de telefonia) se encuentran en usms > proveedores (aun no esta implementado, corresponde a la tabla providers de usms).
Los proveedores se encuentran en un select en lugar de un textbox porque mas adelante se podra cambiar de proveedor directamente en la tabla sin tener que ir a usms > contactos > telefonos y cambiarlo ahi.

**Comment by edwinspire** [comment]
Se encuentra parcialmente implementado. Se puede visualizar los datos existentes en la tabla.
Hay que notar que usms automaticamente ingresa el proveedor obtenido desde el/los modem/s GSM, el CIMI es el numero unico de cada proveedor en el mundo. Lo unico que se deberia cambiar manualmente es el Nombre del proveedor para poderlo identificar facilmente.

**Comment by edwinspire** [comment]
No mas comentarios. Se cierra el tema.
