### ISSUE TITLE
Se encuentra seleccionada por defecto la pestaña "Control de Alarma" en "Abonados/Usuarios"

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#14]
Al entrar a la pestaña "Usuarios" en "Abonados/Usuarios", la pestaña que se encuentra seleccionada por defecto es "Control de Alarma" en lugar de la pestaña "Usuario".  ESto debería ser así, porque la primera acción que se debe realizar al entrar a esa pestaña es ingresar o seleccionar un usuario ya existente.

**Comment by edwinspire** [comment]
Solucionado.
