### ISSUE TITLE
[uSAGA]: Receptor procesando FETCH ALL failed: ERROR:  no existe el esquema «usagasaga» 0 

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#15]
Al ejecutar "./run_opensaga.sh" (le hice los cambios respectivos para que se ejecutara el archivo uSAGA), entre los mensajes que salen en la terminal aparece este:

[uSAGA]: Receptor procesando FETCH ALL failed: ERROR:  no existe el esquema «usagasaga» 0 

No sé si está correcto el mensaje o se trata de un bug, pero por el momento no he visto problemas en el funcionamiento del sistema.

**Comment by edwinspire** [comment]
AL hacer que sucede eso?
Los binarios cambiaron y la base de datos tambien. Actualizarla y probar.

**Comment by Nnino** [comment]
Cambie todos los archivos antes de hacer esta prueba. Sucede al ejecutar el archivo uSAGA en el terminal, como dije anteriormente.

**Comment by edwinspire** [comment]
Recuerdo haber visto ese mensaje ayer, lo revisare mas detenidamente.

**Comment by edwinspire** [comment]
Se solucionó y recompiló uSAGA.
