### ISSUE TITLE
¿Qué son las abreviaciones?

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#16]
Cuál es el significado de la pestaña Abreviaciones que aparece en "Configuración/Formato Notificaciones"

**Comment by edwinspire** [comment]
Abreviaciones son una etiquetas que rpresentan cierta informacio, de momento no las tengo a la mano. Pero por ejemplo el nombre de un abonado es $ABN

**Comment by Nnino** [comment]
Es posible que subas cuales son cuando las tengas a mano?

**Comment by edwinspire** [comment]
Estas estan en la base de datos, sinembargo no todas estan implementadas.

DATOS DE ABONADO
&A01: Grupo
&A02: Subgrupo
&A03: Nombre abonado
&A04: Numero del abonado
&A05: Direccion abonado
&A06: Coordenadas abonado

DATOS DE USUARIO
&U01: Nombre completo
&U02: Numero de telefono (que generó la alarma)
&U03: Tipo de telefono
&U04: Direccion del telefono
&U05: Coordenadas del telefono

DATOS DEL EVENTO
&E01: Descripcion del evento

Esto se pone en notification_templates, ejemplo:
Alarma de &U01

Deberia dar como resultado:
Alarma de De La Cruz Edwin 

Cuando uno crea un notification_template esto genera un idnotiftempl, ese id lo podemos poner en smstext de cada numero a donde se enviará la notificacion con el siguiente formato:

&NT001

Donde 001 es el id mencionado antes en tres digitos.

**Comment by edwinspire** [comment]
-- PREFIJOS
-- &A = Datos del abonado (Account)
-- &AUA = Datos de la direccion del abonado(datos de la tabla address)
-- &AUL = Datos de la localizacion del abonado (datos de la tabla view_locations_full)

-- &AU = Datos del usuario que generó la alarma (datos de la tabla contacts)
-- &AUA = Datos de la direccion del usuario que generó la alarma (datos de la tabla address)
-- &AUL = Datos de la localizacion usuario que generó la alarma (datos de la tabla view_locations_full)

-- &APUA = Datos de la direccion del telefono que generó la alarma (datos de la tabla address)
-- &APUAL = Datos de la localizacion del telefono que generó la alarma (datos de la tabla view_locations_full)

-- &AE = Datos del evento (datos de la tabla usaga.events)

-- Los numeros que siguen al prefijo son dos dijitos que identifican el campo al que se refieren
-- En Abonados > Editar > Contactos > Contacto > Telefonos notificaciones > En el campo smstext colocar por ejemplo:
-- Alarma: &A01 &A02 &A03 &A04 &A05 &AU01 &AU02 &AU03 &AU04 &APU01 &APU02 &APU03 &APU04 &APU05 &APU06 &APU07

--Para probar que los mensajes se generen bien en postgres se puede ejecutar el siguiente query:

select usaga.fun_notification_gen_message(9140, 'Alarma: &A01 &A02 &A03 &A04 &A05 &AU01 &AU02 &AU03 &AU04 &APU01 &APU02 &APU03 &APU04 &APU05 &APU06 &APU07')
-- 9140 es el idevent de la tabla events

**Comment by edwinspire** [comment]
Funcionando
