### ISSUE TITLE
Caracteres en campos "account" y "name" del "Sistema/Monitor de Eventos"

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#17]
Al momento de realizar una modificación en un Abonado, apareció en "Sistema/Monitor de Eventos" unos caracteres (como Ӎ4 o n雺꬀) en los campos "account" y "name" en el registro donde se hizo la modificación (con el mensaje "Actualizada la cuenta idaccount = 1" ).

**Comment by edwinspire** [comment]
Actualizar la base de datos.

**Comment by Nnino** [comment]
Lo hice a la última versión subida pero el problema persiste.

**Comment by edwinspire** [comment]
El problema esta en usaga.fun_view_account_events_xml() de postgres, ya lo soluciono.

**Comment by edwinspire** [comment]
Correccion el problema estaba en usaga.fun_view_last_events_xml();

Este es el codigo de la funcion:

DECLARE

Retorno TEXT DEFAULT '';
CursorResult refcursor;

BEGIN

IF fieldtextasbase64 THEN

OPEN CursorResult FOR SELECT idevent, dateload, CASE WHEN idaccount IS NULL THEN '0' ELSE idaccount END AS idaccount, CASE WHEN partition IS NULL THEN '0' ELSE partition END AS partition, CASE WHEN enable IS NULL THEN 'false' ELSE enable END AS enable, CASE WHEN account IS NULL THEN encode('System'::bytea, 'base64') ELSE encode(account::bytea, 'base64') END AS account, CASE WHEN name IS NULL THEN encode('uSAGA'::bytea, 'base64') ELSE encode(name::bytea, 'base64') END AS name, CASE WHEN type IS NULL THEN '0' ELSE type END AS type, encode(code::bytea, 'base64') as code, zu, priority, encode(description::bytea, 'base64') as description, ideventtype, datetimeevent, encode(eventtype::bytea, 'base64') AS eventtype, process1, process2, process3, process4, process5, dateprocess1, dateprocess2, dateprocess3, dateprocess4, dateprocess5 FROM usaga.view_events ORDER BY idevent DESC LIMIT rows;
SELECT \* FROM cursor_to_xml(CursorResult, 1000, false, false, '') INTO Retorno;
CLOSE CursorResult;

ELSE

OPEN CursorResult FOR SELECT idevent, dateload, CASE WHEN idaccount IS NULL THEN '0' ELSE idaccount END AS idaccount, CASE WHEN partition IS NULL THEN '0' ELSE partition END AS partition, CASE WHEN enable IS NULL THEN 'false' ELSE enable END AS enable, CASE WHEN account IS NULL THEN 'System' ELSE account END AS account, CASE WHEN name IS NULL THEN 'uSAGA' ELSE name END AS name, CASE WHEN type IS NULL THEN '0' ELSE type END AS type, code, zu, priority, description, ideventtype, eventtype, datetimeevent, process1, process2, process3, process4, process5, dateprocess1, dateprocess2, dateprocess3, dateprocess4, dateprocess5 FROM usaga.view_events ORDER BY idevent DESC LIMIT rows;
SELECT \* FROM cursor_to_xml(CursorResult, 1000, false, false, '') INTO Retorno;
CLOSE CursorResult;

END IF;

RETURN '<table>'||Retorno||'</table>';

END;

Reemplazarlo y probar, en la proxina que suba la base de datos estará ya corregido.

**Comment by Nnino** [comment]
Al poner ese código no me muestra los registros en el monitor de eventos

**Comment by edwinspire** [comment]
Veo que algunos caracteres no se copian en este post, que raro, ya subi la base de datos con la correccion.
