### ISSUE TITLE
El botón Guardar de "usms/Contactos" no funciona correctamente

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#18]
Al tratar de modificar los datos de un contacto en "usms/Contactos", el botón guardar no funciona.

**Comment by Nnino** [comment]
Mmm... probando de nuevo, ahora si funcionó... pero de vez en cuando tiene bug y no guarda

**Comment by edwinspire** [comment]
Trataré de replicarlo, hasta ahora no me ha dado ese problema.
