### ISSUE TITLE
Alert al hacer click en el campo "provider" en "Abonados/Usuarios/Control de Alarma" 

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#19]
Al hacer click 3 veces en el campo "provider" y luego un click fuera del campo, sale un alert diciendo "No hay datos que ingresar".

**Comment by edwinspire** [comment]
No he podido obtener ese mismo resultado aqui, sinembargo ese mensaje sale cuando en los campos sms, call, y smstext estan vacios, o sea en realidad la base de datos interpreta como que no hay datos que setear, esto en registros que anteriormente no se han seteado con datos.

**Comment by edwinspire** [comment]
No se ha podido reproducir el bug.
