### ISSUE TITLE
También me gustaría saber si es posible que dividas visualmente la dirección del Abonado en 5 campos separados

### ISSUE THREAD

**Issue by edwinspire** [edwinspire/usaga#20]
También me gustaría saber si es posible que dividas visualmente la dirección del Abonado en 5 campos separados:
- Calle
- Departamento
- Número/Block
- Población, Barrio o Sector
- Cuadrante

**Comment by edwinspire** [comment]
Se está implementando:
Pais
Estado / Provincia
Ciudad
Sector
Subsector
Calle principal
Calle transversal
Otros (detalles)

Esto para hacer el software mas adaptable a otros paises de una forma mas general.

**Comment by edwinspire** [comment]
Debido a la reimplementacion de las direcciones las notificaciones via sms no estan funcionando correctamente.

**Comment by Nnino** [comment]
Edwin, se te pidió con esas direcciones, porfavor, sigue lo que se te dijo...

**Comment by Nnino** [comment]
Qué módulo especificamente es el que no está funcionando y cuáles tienen bug?

**Comment by edwinspire** [comment]
Bugs he resulto la mayoria.
Las platillas de notificaciones no funcionan las abreviaciones relacionadas con las direcciones.

**Comment by Nnino** [comment]
Cuando no hay dirección escrita en los contactos salen caracteres raros y aún veo que no corresponde el evento con su tipo en el monitor de eventos

**Comment by Nnino** [comment]
Ah, al salir de un módulo se queda marcado el botón del menú, y cuando se selecciona otro módulo quedan marcados ambos botones

**Comment by edwinspire** [comment]
Modificando.
