### ISSUE TITLE
Duda respecto al envío de los SMS

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#24]
Es normal que el sistema a veces envíe todos los SMS o a veces envíe la mitad

**Comment by edwinspire** [comment]
No, no es normal, puede ser algun problema con las fechas o que tiene problemas al enviarlos.

**Comment by Nnino** [comment]
Es posible que revises cuál es el problema con el envio de los SMS?... probé generando una alerta, y de las 2 personas que debian recibir los SMS, sólo 1 recibió. Actualicé todos los archivos a su última versión. 

Respecto a la fecha de los SMS, esta es de mañana, no de hoy como debería ser, no sé si eso tendrá que ver con el problema.

**Comment by edwinspire** [comment]
En la base de datos ta,bien se muestran los mejsajes con la fecha de 
mañana o solo en la interface web?

**Comment by Nnino** [comment]
Sólo en la interface web

**Comment by edwinspire** [comment]
Es un problema con javascript, no el la razon de la inestabilidad del 
los sms. La visualizacion ya la corrigo.

**Comment by edwinspire** [comment]
En que pagina exactamente esta el problema de las fechas de los sms?

**Comment by Nnino** [comment]
En las paginas de SMS entrantes, SMS salientes y llamadas entrantes

**Comment by edwinspire** [comment]
Corregidas  las fechas en la pagina usms_smsout.html

**Comment by Nnino** [comment]
Otro detalle con los SMS, es que algunos caracteres, como por ejemplo la ñ o acentos, no se envian correcrtamente

**Comment by edwinspire** [comment]
Solucionado, revisar.

**Comment by Nnino** [comment]
Ahora se muestra correctamente las fechas

**Comment by edwinspire** [comment]
Ese es mas bien manejado por el modem gsm. Usando minicom enviar el 
comando:
AT+CSCS?
AT+CSCS=?
Esto es para ver el set de caracteres soportado por el modem. Pero 
recuerdo que en su momento ya habiamos probado esto y tenia soporta para 
UCS2.

**Comment by Nnino** [comment]
Lo que envió el modem:

AT+CSCS  
+CSCS: "IRA"

**Comment by edwinspire** [comment]
AT+CSCS? deberia devolver una lista, si el modem solo soporta IRA 
entonces los caracteres especiales no van a poder ser enviados 
correctamente.
Que responde al comando AT+CSCS?
Luego que responde al comando AT+CGMF?
Y Al comando ATI3

**Comment by Nnino** [comment]
Al comando AT+CSCS responde IRA. Al comando AT+CGMF responde error. Al comando ATI3 responde Telit

**Comment by Nnino** [comment]
Acá se había hecho un cambio de modem por otro de las mismas características al anterior. Se configuró con los comandos "AT", "AT#BND=1 "y "AT+CREG". No sé si habrá hecho falta otro comando y por eso tiene errores.

**Comment by edwinspire** [comment]
Un error mio, El comando era
AT+CMGF?

**Comment by edwinspire** [comment]
Estoy probando aca el envio de sms tambien, hasta ahora solo he tenido 2 
errores al enviar. Que marca y modelo de modem está usando?

**Comment by Nnino** [comment]
El comando AT+CMGF responde 0

**Comment by Nnino** [comment]
Se esta usando un "Módulo Celular GSM/GPRS GM862 QuadBand"

**Comment by edwinspire** [comment]
El modem no es igual al que iniciamos las pruebas. Solo soporta modo 
PDU. Haré unos ajustes y los subo.

**Comment by Nnino** [comment]
Mmm... estuve mirando el módem que estaba cuando yo llegué y es igual. Como era el módem con el que se realizaron las pruebas?

**Comment by edwinspire** [comment]
No recuerdo exactamente la marca y modelo, pero soportaba modo Texto y 
PDU (AT+CMGF?), y el set de caracteres era de mas amplio, soportaba UCS2 
que facilita el envio de caracteres especiales, como tildes, ñ, etc.

**Comment by edwinspire** [comment]
Sin embargo se puede ajustar, o se debe ajusta a cualquier modem GSM, es 
compatible haciando algunos cambios pequeños.

**Comment by Nnino** [comment]
Los cambios que hay que hacer son en el programa o configurando de otra manera el modem?

**Comment by edwinspire** [comment]
Los cambios son en el programa

**Comment by edwinspire** [comment]
Se han realizado algunos cambios para ajustarse al standar de modems gsm, aunque no todos los modems los cumplen totalmente. Probar e informar si ha ,ejorado.

**Comment by Nnino** [comment]
Ha mejorado en relación a los caracteres especiales, ya que ahora se envían correctamente. 

Lo que aún no mejora es el envío de SMS, ya que aún no es posible que los envíe todos. Viendo los registros de los SMS salientes y entrantes, en los entrantes sale el mensaje de la compañia que indica que todos los SMS fueron recibidos por los respectivos teléfonos, sin embargo en los salientes, el SMS que no se envió aparece con el número 8 en el campo process.

**Comment by edwinspire** [comment]
-- process:
0 nada,
1 blockeado,
2 enviado,
3 falla,
4 destino no permitido,
5 autoprovider,
6 enviado incompleto,
7 expirado tiempo de vida,
8 falla todos los intentos por enviar por todos los puertos,
9 fallan todos los intentos de envio,
10 Espera por reintento de envio,
11 Phone no valido

**Comment by Nnino** [comment]
De qué manera se puede solucionar eso, o es un problema que ya no depende del modem y/o programa?

**Comment by edwinspire** [comment]
Se puede aumentar el numero de intentos de envio.
Una pregunta... el texto de ese mensaje en ocaciones se envia y en otras 
no? o pasa con determinado texto o numero telefonico?

**Comment by Nnino** [comment]
No depende ni del número telefónico ni del texto enviado, ya que en otras ocasiones el mismo teléfono recibe el SMS con el mismo texto sin problemas.

**Comment by edwinspire** [comment]
ok, en algunos modems requieren de un tiempo de unos segundos para 
volver a enviar un sms, aumentaré el numero de intentos de envio.

**Comment by Nnino** [comment]
Ok

**Comment by Nnino** [comment]
Una pregunta respecto a los caracteres especiales, cuáles son los caracteres soportados? . Ya que probé con el carácter " ° " y en su lugar se envió un "?".

**Comment by edwinspire** [comment]
Para modems que solo soportan modo PDU como el suyo, tiene algunas 
limitaciones, si el mensaje tiene menos de 70 caracteres se usa el set 
de caracteres UCS2, si el mensaje es mayor de 70 y menor que 140 usa 
codoficacion de 8 bits (Este he probado y no me ha funcionado con ningun 
modem, llega como "MENSAJE NO SOPORTADO"), si el mensaje es mayor de 140 
caracteres usa codificacion de 7 bits (The 7 bit default alphabet).
uSMS hace automaticamente la seleccion del set de caracteres a usar.
Envio un adjunto, espero que llegue.

**Comment by edwinspire** [comment]
Los caracteres permitidos los pueden ver en:
http://www.developershome.com/sms/gsmAlphabet.asp
http://en.wikipedia.org/wiki/GSM_03.38

El resto de caracteres son reemplazados por un "?"

**Comment by edwinspire** [comment]
Que tiempo están tardando los mensajes desde que se hace la  llamada a uSAGA hasta que llega la notificación?

**Comment by Nnino** [comment]
Unos 10 segundos más o menos.

**Comment by edwinspire** [comment]
El tiempo es bastente bueno. Aca les toma 15 a 20 segundos. Trataré de 
mejorar el tiempo, pero no es critico por el momento.

**Comment by Nnino** [comment]
Ok
