### ISSUE TITLE
Notificaciones de Direccion

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#25]
Está contemplado implementar las notificaciones para que se envíe la dirección del abonado o usuario en el SMS?, de ser así para que día sería y cuál de todos los campos involucrados en la dirección se enviaría en el SMS?....

**Comment by edwinspire** [comment]
Estoy trabajando en eso. Los campos involucrados e la direccion serían 
los que vean convenientes. Se crearia una plantilla de sms y en ella se 
pondrian los datos que se deseen. Para la direccion hay 10 campos, todos 
ellos podrán formar parte de la direccion o los que se seleccione.

**Comment by edwinspire** [comment]
-- PREFIJOS
-- &ACC = Datos del abonado (Account)
-- &ACCU = Datos del usuario que generó la alarma (datos de la tabla contacts)
-- &ACCAU = Datos de la direccion del usuario que generó la alarma (datos de la tabla address)
-- &ACCLU = Datos de la localizacion usuario que generó la alarma (datos de la tabla view_locations_full)
-- &ACCAUP = Datos de la direccion del telefono que generó la alarma (datos de la tabla address)
-- &ACCLUP = Datos de la localizacion del telefono que generó la alarma (datos de la tabla view_locations_full)

-- Los numeros que siguen al prefijo son dos dijitos que identifican el campo al que se refieren
-- En Abonados > Editar > Contactos > Contacto > Telefonos notificaciones > En el campo smstext colocar por ejemplo:
-- Alarma: &ACC01 &ACC02 &ACC03 &ACC04 &ACC05 &ACCU01 &ACCU02 &ACCU03 &ACCU04 &ACCPU01 &ACCPU02 &ACCPU03 &ACCPU04 &ACCPU05 &ACCPU06 &ACCPU07

--Para probar que los mensajes se generen bien en postgres se puede ejecutar el siguiente query:

select usaga.fun_notification_gen_message(9140, '&ACC01 &ACC02 &ACC03 &ACC04 &ACC05 &ACCU01 &ACCU02 &ACCU03 &ACCU04 &ACCPU01 &ACCPU02 &ACCPU03 &ACCPU04 &ACCPU05 &ACCPU06 &ACCPU07')
-- 9140 es el idevent de la tabla events

**Comment by edwinspire** [comment]
-- PREFIJOS
-- &A = Datos del abonado (Account)
-- &AUA = Datos de la direccion del abonado(datos de la tabla address)
-- &AUL = Datos de la localizacion del abonado (datos de la tabla view_locations_full)

-- &AU = Datos del usuario que generó la alarma (datos de la tabla contacts)
-- &AUA = Datos de la direccion del usuario que generó la alarma (datos de la tabla address)
-- &AUL = Datos de la localizacion usuario que generó la alarma (datos de la tabla view_locations_full)

-- &APUA = Datos de la direccion del telefono que generó la alarma (datos de la tabla address)
-- &APUAL = Datos de la localizacion del telefono que generó la alarma (datos de la tabla view_locations_full)

-- &AE = Datos del evento (datos de la tabla usaga.events)

-- Los numeros que siguen al prefijo son dos dijitos que identifican el campo al que se refieren
-- En Abonados > Editar > Contactos > Contacto > Telefonos notificaciones > En el campo smstext colocar por ejemplo:
-- Alarma: &A01 &A02 &A03 &A04 &A05 &AU01 &AU02 &AU03 &AU04 &APU01 &APU02 &APU03 &APU04 &APU05 &APU06 &APU07

--Para probar que los mensajes se generen bien en postgres se puede ejecutar el siguiente query:

select usaga.fun_notification_gen_message(9140, 'Alarma: &A01 &A02 &A03 &A04 &A05 &AU01 &AU02 &AU03 &AU04 &APU01 &APU02 &APU03 &APU04 &APU05 &APU06 &APU07')
-- 9140 es el idevent de la tabla events

**Comment by Nnino** [comment]
El código &APU que usas en el ejemplo, a que datos corresponde?

**Comment by edwinspire** [comment]
APU = ACCOUNT PHONE USER
Datos del telefono del usuario que generó la alarma.

**Comment by Nnino** [comment]
Al usar el codigo &AU03 y &AU04 (que según lo que mencionaste vendrían siendo el firstname y lastname), sale en su lugar el title y el firstname respectivamente

**Comment by edwinspire** [comment]
-- PREFIJOS
-- &A = Datos del abonado (Account)
-- &AA = Datos de la direccion del abonado(datos de la tabla address)
-- &AL = Datos de la localizacion del abonado (datos de la tabla 
view_locations_full)
  son los correctos.
Todo eso esta en la funcion  usaga.fun_notification_gen_message();

**Comment by edwinspire** [comment]
Voy a revisar. Igual lo pueden revisar en la funcion
fun_contact_getdata_string() de postgres, ahi esta la programacion de 
relacionada.

**Comment by edwinspire** [comment]
Favor cerrar el hilo si ya no ha dado problemas.

**Comment by Nnino** [comment]
Aún sigue el problema que mencioné al usar el codigo &AU03 y &AU04 (que según lo que mencionaste vendrían siendo el firstname y lastname), sale en su lugar el title y el firstname respectivamente.

**Comment by edwinspire** [comment]
En la interface grafica aun no he puesto exactamente las abreviaciones 
para cada campo,  no todos los campos están habilitados, sin embargo en
la funcion fun_contact_getdata_string(), fun_address_getdata_string(), 
fun_location_getdata_string(), están exactamente los numeros de los 
campos que se pueden obtener.

**Comment by Nnino** [comment]
Respecto a eso una duda, las abreviaciones se podrán usar posteriormente en el módulo de Notificaciones como antes?

**Comment by edwinspire** [comment]
Usando la abreviación &NTXXX donde XXX es el idnotiftempl?

**Comment by Nnino** [comment]
Sí

**Comment by edwinspire** [comment]
Ya está implementado, si existe algun problema comuniquenlo.

**Comment by Nnino** [comment]
No funcionó cuando lo probé. Llegan los SMS con el texto &NT001 (el idnotiftempl es 1).

**Comment by edwinspire** [comment]
ya lo reviso

**Comment by edwinspire** [comment]
en usaga.fun_notification_gen_message();

cambia la siguiente linea:

idnt :=  to_number((regexp_matches(Retorno, '&NT(\d\d)'))[1], '999');

por:

idnt :=  to_number((regexp_matches(Retorno, '&NT(\d\d\d)'))[1], '999');

Ya subo los cambios.

**Comment by Nnino** [comment]
Ya funciona correctamente

**Comment by Nnino** [comment]
Queda pendiente entonces, mostrar los códigos de cada notificación en la interfaz

**Comment by edwinspire** [comment]
ok

**Comment by edwinspire** [comment]
Ya están los cambios en la interface gráfica.
