### ISSUE TITLE
Error al ejecutar usaga

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#27]
Al ejecutar usaga, sale el siguiente error en consola:

Error binding to address: Address already in use
El servidor muere...

Este problema no sucede al ejecutar usms.

**Comment by Nnino** [comment]
Probando de nuevo, sólo puede funcionar a la vez usaga o usms, ya que si se les trata de hacer funcionar al mismo tiempo, da ese error.

**Comment by edwinspire** [comment]
Las dependencias de usaga, principalmente libspire_uhttp y libspire_usms 
se han modificado.
Revisar
https://github.com/edwinspire/libspire_uhttp/issues/1
https://github.com/edwinspire?tab=activity

**Comment by edwinspire** [comment]
Esto se debe a que usaga y usms están usando el mismo puerto, por eso 
solo uno puede funcionar.
Existe un archivo nuevo llamado uhttp.conf, de fabrica el puerto es 
8080, en usaga cambiarlo a 8081 e intentar nuevamente arrancar el programa.

**Comment by Nnino** [comment]
Existe un archivo uttp.conf para usms y uno para usaga?... Porque cambiando
lo que me dijiste, aún así no funciona.

**Comment by edwinspire** [comment]
Si, existe uno para usms y otro para usaga.
Deberian correr en carpetas separadas para que no haya problema.

**Comment by Nnino** [comment]
Entonces solamente los ejecutables con sus respectivos archivos uhttp.conf
deberían ir en carpetas separadas?. Ya que este tiempo se estuvo trabajando
con los archivos de ambos programas juntos en la misma carpeta.

2013/3/19 Edwin De La Cruz notifications@github.com

**Comment by edwinspire** [comment]
Este cambio se lo realizó para poder cambiar facilmente los parametros 
del microservidor web sin tener que recompilar. Para usar por ejemplo el 
puerto 80 que normalmente se usa para http.
uSAGA y uSMS deben estar en carpetas separadas cada uno con las 
librerias y archivos.
No es necesario que uSMS contenga la carpeta rootweb ya que todos los 
archivos tambien estan en uSAGA.

**Comment by Nnino** [comment]
Ok, los cambios se realizaron y ya funcionan ambos.

**Comment by edwinspire** [comment]
Muy bien.
