### ISSUE TITLE
Duda respecto a la prioridad al enviar un SMS

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#30]
Una duda, funciona la prioridad al enviar los SMS de un abonado? Y si es así, funciona la prioridad del teléfono o la prioridad del contacto?

**Comment by edwinspire** [comment]
Ahora que lo reviso no está implementado aun. El mensaje "uSAGA ha 
recibido su señal" es el unico que tiene prioridad 10, se envia al final.

**Comment by edwinspire** [comment]
Estaba recordando acerca de esto, La prioridad de los contactos se 
refiere unicamente cuando un "operador" debe tomar contacto con el 
contacto telefonicamente, entonces el operador hará las llamadas en el 
orden de prioridad que el cliente haya solicitado.
El mismo caso es para la prioridad de los teléfonos, para el caso de 
notificaciones automaticas via sms (alarmas comunitarias) estos campos 
no son tomados en cuenta.
