### ISSUE TITLE
Error con el mensaje "Se aplicó los cambios a X teléfonos de X de X contactos solicitados."

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#31]
Al modificar varios contactos de un abonado a la vez en "Contactos/Editar/Lista", el mensaje que da luego de hacer los cambios, no corresponde con el número de cambios que se realiza realmente. 

Por ejemplo si tengo 3 contactos, cada uno con un número telefónico, entonces el mensaje es el siguiente.
"Se aplicó los cambios a 6 teléfonos de 3 de 3 contactos solicitados."

**Comment by Nnino** [comment]
Otra cosa, al seleccionar todos los contactos por medio del botón, se van mostrando alert indicando la cantidad de contactos que se seleccionaron. Es posible que una vez que el programa ya se encuentre en una versión más estable, se puedan sacar esos diálogos? Ya que supongo que esos alert son de prueba y no deberían mostrarse al usuario final.

**Comment by edwinspire** [comment]
Los dialogos son unicamente para depuración. se los eliminará mas adelante.

**Comment by edwinspire** [comment]
Se reparó este bug.

**Comment by edwinspire** [comment]
Solucionado
