### ISSUE TITLE
Duda respecto a Geox y Geoy.

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#32]
En el módulo Localización (usaga/Abonados/Editar/Localización) cuando se guarda una dirección nueva, el sistema no permite agregarla si es que no se encuentran definidos los campos Geox y Geoy. Mi pregunta es, si es necesario que sea así?

**Comment by Nnino** [comment]
Esto también sucede en los módulos Localización en uSMS.

**Comment by edwinspire** [comment]
de fábrica esos campos son 0, deben tener algun valor para poderlos 
enviar a la base de datos.

**Comment by edwinspire** [comment]
El modulo LOCALIZACION  es comun para todos. Cualquier cambio hecho en 
el modulo se verá reflejado en todo el sistema, uSAGA y uSMS

**Comment by edwinspire** [comment]
He probado sin embargo no he tenido problema al ingresar una 
lozalizacion nueva. Cuando no ingreso datos los campos se guardan como 0.

**Comment by Nnino** [comment]
Cuando lo he probado acá, los textfield de los campos geox y geoy cambian a color rojo y no se almacena la dirección si es que no ingreso algún valor.

**Comment by edwinspire** [comment]
Es correcto, cuando algun campo de un formulario está en rojo, indicando 
algun error en el dato entonces el formularo no se envia al servidor y 
por ende no es guardado en la base de datos. Cambiaré eso para que 
siempre haya un valor de 0 en esos campos.

**Comment by Nnino** [comment]
Ok

**Comment by edwinspire** [comment]
Solucionado
