### ISSUE TITLE
Error al eliminar un abonado

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#33]
Al tratar de eliminar un abonado sale el mensaje "El nombre no es válido" y no elimina el abonado. Este error se repite también en la última versión.

**Comment by edwinspire** [comment]
El problema estaba en  usaga.fun_account_table_xml() en la base de datos.
cabo de subir la correción.

**Comment by Nnino** [comment]
Qué error específicamente tenia esa función?

**Comment by edwinspire** [comment]
Hacia una verificación de la longitud del nombre de la cuenta antes de 
hacer cualquier operación, insertar, modificar o eliminar. Ahora solo 
hace esa verificación cuando se va a insertar o actualizar, no para 
eliminar un registro.

**Comment by Nnino** [comment]
Ok, gracias... ya está solucionado
