### ISSUE TITLE
Error al hacer una llamada

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#34]
Al realizar una llamada al modem, el sistema la detecta y la almacena, pero no genera ninguna alarma. En la terminal donde corre usms aparece el siguiente log:

"Llamada entrante detectada y almacenda: +569946xxxx
AT+CREG?
+CREG: 0,1

OK
Network REG EDWINSPIRE_GSM_MODEM_NETWORK_REGISTRATION_UNSOLICITED_RESULT_CODE_Disable => EDWINSPIRE_GSM_MODEM_NETWORK_REGISTRATION_STATUS_Registered
AT+CMGF=1
OK

*\* (process:4075): WARNING **: libspire_serial.vala:510: [ReadLineWithoutStrip] Timeout to End Line, limit 366.66666666666669 ms"

Luego de esto, no hace nada más y sale que no hay SMS pendientes para enviar. Tampoco aparece en la terminal de usaga que el evento fue generado y la llamada recibida, como antes. Ahora aparece siempre con este formato: 

[uSAGA]: Generando reportes de prueba automaticos
Eventos generados: 

[uSAGA]: Generando reportes de prueba automaticos
Eventos generados:

**Comment by edwinspire** [comment]
El número telefonico +569946xxxx almacenado en la base de datos coincide 
con el de algun contacto?
Porque veo que el numero estpa en formato internacional, inicia con el + 
y el codigo de pais.
Si la operadora o el modem detecta de esta manera los telefonos en los 
contactos deberian ser ingresados los telefonos igualmente.

**Comment by edwinspire** [comment]
Para chequear que la llamada fue asignada a un contacto en la tabla 
incomingcalls en el registro de esa llamada en idphone debería aparecer 
algún valor mayor que 0, que es el id del teléfono almacenado en la base 
de datos.

**Comment by Nnino** [comment]
Si, de hecho hicimos una prueba con el sistema en un estado anterior, con los mismos números telefónicos y no daba ningún problema. En cambio al probarlo con la última versión, aunque se encontrara registrado el número no lo detectaba

**Comment by edwinspire** [comment]
Pero en la tabla incomingcalls en el campo idphone esta registrado un 
valor mayor a 0?

**Comment by Nnino** [comment]
Mmm... no podría decirte en este momento, ya que no tengo acceso al sistema.

**Comment by edwinspire** [comment]
Es un poco extraño porque en uSMS no hubo cambios en esa área, hay que chequear si el numero que se registra coincide con el numero de algun contacto. uSMS hace una simple comparación de cadenas entre el numero detectado y los numeros guardados en la tabla phones para asignar el idphone.

**Comment by fizzvr** [comment]
:+1:

**Comment by Nnino** [comment]
El error aún persiste, incluso en la última versión. Estuve viendo la tabla de llamadas entrantes, pero reconoce sin problemas la id del teléfono que hizo la llamada y en el campo f1 sale el valor 2.

**Comment by edwinspire** [comment]
flag1 = 2
-- La llamada no pertenece a ningun abonado

**Comment by edwinspire** [comment]
Hay que estar seguros de que ese idphone pertenesca a alguna cuenta y 
este habilidata para generar la alarma.
La consulta que hace este chequeo es

SELECT idaccount FROM usaga.view_account_phones_trigger_alarm WHERE 
idphone = VROWDATA.idphone AND enable = true AND trigger_enable = true 
AND fromcall = true LIMIT 1;

Deben cambiar VROWDATA.idphone por el idphone de la llamada y debe 
devolverles a que cuenta petenece ese numero, si devuelve 0 o null esque 
no ha sido asignada.

**Comment by Nnino** [comment]
Mmm... Si, ahi funcionó. Gracias
