### ISSUE TITLE
Respecto a la geolocalización

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#35]
Estuve probando la geolocalización, pero la dirección que me mostraba en el mapa no era la correcta. 
Pienso que quizás es porque en los campos que se encuentran las coordenadas, sólo se permiten valores numéricos, siendo que las coordenadas contienen además una dirección (norte, sur, este u oeste) y además no solamente se representa con grados, sino que también por minutos y segundos.

**Comment by edwinspire** [comment]
El formato de las cordenadas en en formato decimal, latitud y longitud.
Pueden abrir http://www.openstreetmap.org/  y buscar una direccion en el 
mapa, una vez ubicada hacer click en la parte inferior derecha en donde 
dice Shortlink, en la direccion url van a obtener la latitud y longitud.

http://www.openstreetmap.org/?lat=-0.21200180053710938&lon=-78.39603424072266&zoom=13

**Comment by Nnino** [comment]
Aaah ok... ya entendí. Hay alguna manera de ver las calles en este mapa?. Porque señalé una posición pero el mapa se muestra en blanco.

**Comment by edwinspire** [comment]
Puede ser que el zoom este muy alto en la parte superior izquierda del 
mapa hay un signo de mas y menos, presionar menos hasta que aparesca el 
mapa.

**Comment by edwinspire** [comment]
Si las calles del lugar que uno desea ver aun no están señalizadas es 
posible agregarlas uno mismo, es una ventaja de openstreetmap, los 
cambios serán visibles para todo el mundo. Eso no se podia hacer con 
googlemaps.
