### ISSUE TITLE
Error al eliminar un Contacto

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#36]
Cuando se trata de eliminar un contacto da el siguiente error: "El número de identificación 12333111-2 tipo 3 ya existe en otro contacto, verifique los datos".
Este mensaje no coincide con lo que sucede, ya que no hay otro contacto con el cual coincida el número de identificación.

**Comment by edwinspire** [comment]
Solucionado, problema estaba en la base de datos. Actualizar.
