### ISSUE TITLE
Mensaje de error al ingresar en el módulo Abonados

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#38]
Al presionar el botón "Abonados" del menú, aparece el siguiente mensaje de error: "RequestError: Unable to load usms_provider_listidname_xml status: 404"

**Comment by edwinspire** [comment]
Estaba haciendo unos cambios en un modulo - usar la libreria 
libspire_usms que estaban usando anteriormente.

**Comment by edwinspire** [comment]
Pueden usar ya la libreria libspire_usms mas reciente.

**Comment by edwinspire** [comment]
Cerrar el hilo si se ha solucionado el problema.

**Comment by Nnino** [comment]
Gracias, ya se encuentra solucionado
