### ISSUE TITLE
uSMS - No se puede agregar nuevos telefonos

### ISSUE THREAD

**Issue by edwinspire** [edwinspire/usaga#40]
Al intentar agregar telefonos a un contacto que no tenia telefonos anteriormente no lo permite, se muestra mensaje contacto no encontrado.

**Comment by edwinspire** [comment]
Solucionado

**Comment by Nnino** [comment]
Aún persiste el problema de que no se puede ingresar el teléfono

**Comment by edwinspire** [comment]
Bajar nuevamente e intentar, hace poco  lo volvi a subir

**Comment by Nnino** [comment]
Lo bajé de nuevo pero no funciona

**Comment by edwinspire** [comment]
OK, volvi a subir un cambio, revisar.

**Comment by edwinspire** [comment]
Creo que ya encontre la falla
