### ISSUE TITLE
Visualización de encabezado de tabla eventos en módulo Abonados

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#41]
En el módulo Abonados, al final de la página (si uno hace scroll) se ve el encabezado de la tabla Eventos.

**Comment by Nnino** [comment]
Y está bien que al entrar al programa uSAGA o uSMS no aparezca nada?

**Comment by edwinspire** [comment]
Revisaré.
Respecto a la entrada de uSAGA y uSMS aparecen de momento vacias porque ahi va a ir el logging.

**Comment by edwinspire** [comment]
Solucionado.
