### ISSUE TITLE
Error al ejecutar usms

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#42]
Al ejecutar usms en la terminal, sale el siguiente error:

./usmsd: error while loading shared libraries: libspire_crypto.so: cannot open shared object file: No such file or directory

**Comment by edwinspire** [comment]
Ya se elimino la dependencia libspire_crypto

**Comment by Nnino** [comment]
En qué parte fue eliminada?

**Comment by edwinspire** [comment]
Estaba haciendo unas pruebas en uSMS para el logging.
Se recompiló usms.

**Comment by edwinspire** [comment]
Solucionado
