### ISSUE TITLE
Error con un chip en programa uSMS

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#43]
Al usar un determinado chip de teléfono celular, se ve el siguiente log en la terminal del programa uSMS. Cuando sale este log, no se pueden recibir alertas.
Cuando cambiamos el chip por otro chip de celular, el error no sucede, por lo que no sé si el error tiene algo que ver con el chip o el programa. Y qué significa el error exactamente

![img](https://f.cloud.github.com/assets/3172011/473553/46af08b6-b750-11e2-853d-a563738495e2.png)

**Comment by edwinspire** [comment]
Cuando hacen el cambio de chip cierran el programa, apagan el modem, 
hacen el cambio de chip y luego reinician todo?
El chip es de la misma operadora?
El chip tiene activado el PIN, osea tiene clave?
Segun el log pareceria ser problema de comunicacion con el modem o que 
no puede acceder al chip.

**Comment by Nnino** [comment]
El mismo chip era usado hace poco para hacer pruebas, pero ahora da ese problema. El programa se cierra y se apaga el modem para hacer el cambio de chip y todos los chip que tenemos son de la misma operadora. El chip no tiene clave y tampoco se ha modificado eso, como mencioné al principio, es el mismo chip que hemos estado usando para las pruebas el que ahora no funciona. Este chip lo pusimos en un celular y funciona sin problemas, incluso se pueden enviar mensajes desde él.

**Comment by edwinspire** [comment]
Intenten usar el chip con minicom para ver si hay problema tambien con él

**Comment by Nnino** [comment]
El chip en minicom responde sin problemas.

**Comment by edwinspire** [comment]
Pero con otro chip si funciona el programa?
De todos modos voy a revisar, aunque ultimamente no he realizado cambios 
en uSMS ni librerias relacionadas

**Comment by Nnino** [comment]
Si, con otro chip funciona bien.

**Comment by Nnino** [comment]
Al escribir en minicom "AT+CMGL=4" da una lista de mensajes con el formato +CMGL: X,1,160 (el número X es el número del mensaje) , que es la que se muestra en el error. En el chip que  funciona bien, al escribir el mismo comando, da OK y no la lista de mensajes.

**Comment by edwinspire** [comment]
Entonces podria ser algun problema con el chip, hace tiempo me ocurrio 
algo parecido y era debido a que en los mensajes recibidos habia uno que 
tenia como adjunto un sonido, lo mismo pasaba cuando contenian tonos o 
alguna clase de adjunto y no era un sms de solo texto. Probar a eliminar 
todos los mensajes guardados en el chip e intentar nuevamente.
