### ISSUE TITLE
Duda sobre la version de desarrollo

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#51]
Es posible probar la versión de desarrollo tal cual como se encuentra actualmente?.. y si es así, hay que probarla con las librerías y archivos faltantes de la versión estable?

**Comment by edwinspire** [comment]
Si es posible probr la version de desarrollo, hay que bajarla igual que 
la master.
Las librerias que hay que bajar son las de desarrollo: libspire_usms, el 
resto de librerias son las que estan tambien disponibles en github pero 
en las ramas master.
Posiblemente la rama de desarrollo mañana o a mas tardar pasado mañana 
la suba a la rama master (estable).

**Comment by edwinspire** [comment]
uSAGA ya no depende de uSMS, uSMS está incluido dentro de uSAGA.
Simplemente correr uSAGA como se lo hacia hasta ahora, bajar las 
librerias actualizadas, libspire_usms bajarla de la rama develop junto 
con el resto de librerias de la rama master.

**Comment by Nnino** [comment]
Estuve probando lo que dijiste, bajando los archivos mencionados y copiandolos en las carpetas. Yo he tratado de ejecutar el programa uSAGA con un archivo llamado run_usaga.sh que contiene lo siguiente:

 #!/bin/bash

export LD_LIBRARY_PATH=.

export LD_LIBRARY_PATH="/home/debian/Escritorio/usms_opensaga_Actual_beta/uSAGA"
./uSAGA

Este archivo siempre funcionó en el pasado, pero el problema es que al ejecutarlo ahora, me da el siguiente error en la consola:

bash: ./run_usaga.sh: /bin/bash^M: intérprete erróneo: No existe el fichero o el directorio

**Comment by edwinspire** [comment]
No he logrado reproducir el problema.
Aún persiste?

**Comment by Nnino** [comment]
Si, aún da problemas con ese comando. Hay una manera de ejecutar uSAGA directamente en la consola sin usar ese archivo run_usaga.sh?

**Comment by edwinspire** [comment]
Si, colocar todas las librerias junto con el ejecutable uSAGA.
Desde consola ejecutar ./usaga

Estoy ya subiendo la nueva version.
Esta lista en unos minutos, probarla.

**Comment by Nnino** [comment]
Puse las librerías junto al ejecutable, pero me sale lo siguiente:

./uSAGA: error while loading shared libraries: libspire_serial.so: cannot open shared object file: No such file or directory

**Comment by edwinspire** [comment]
Hay que ejecutar esto en consola:

export LD_LIBRARY_PATH=.

export 
LD_LIBRARY_PATH="/home/edwinspire/programacion/ProyectosSoftware/Software Vala/ProyectosVala/proyectlibs/lnx"
./uSAGA

export LD_LIBRARY_PATH= Es el Path donde esta uSAGA

**Comment by edwinspire** [comment]
La rama DEVELOP que estaba hasta la fecha a pasado a la rama MASTER
