### ISSUE TITLE
Duda sobre el funcionamiento del uSAGA

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#52]
En la empresa, hemos notado que al quedarse suspendido Debian el sistema de alarma ya no funciona y no recibe llamadas ni envía mensajes. 
Entonces la consulta es si es posible evitar que Debian se suspenda, para que así el sistema pueda funcionar sin estar necesariamente usando el computador que lo aloja.

**Comment by edwinspire** [comment]
Saludos, he estado sin internet mas de una semana.

En Herramientas del Sistema > Preferencias > Administracion del sistema 

> Energía
> En las opciones elegir NO SUSPENDER.

**Comment by Nnino** [comment]
Muchas gracias Edwin. Ahí logramos que no se bloqueara ni suspendiera.
Saludos
