### ISSUE TITLE
Sugerencia acerca del campo Proveedor en uSMS/Contactos/Teléfonos

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#53]
Es posible que el campo Proveedor en uSMS/Contactos/Teléfonos ya no sea un campo obligatorio para ingresar un nuevo teléfono?

**Comment by edwinspire** [comment]
lo cambiaré

**Comment by Nnino** [comment]
Ok, gracias

**Comment by edwinspire** [comment]
Se hizo un cambio en la base de datos para modificar esta opción.
Sigue siendo requerida pero en caso de no haber proveedores elegir "Ninguno"
