### ISSUE TITLE
Problema al enviar SMS luego de generar una alarma

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#54]
Hicimos una prueba generando una alarma con la última versión subida y aunque reconoce el número que realizó la llamada (sale en los registros de llamadas entrantes) y se generaron los SMS (sale en los registros de SMS salientes), no se hace envío de los SMS.

Recuerdo que antes había un valor en los registros de los SMS salientes que me permitía saber si los SMS se habían enviado correctamente, pero veo que cambiaste los campos que se muestran en la tabla, por lo cual no sé ahora cual podría ser exactamente el problema.

Además el navegador me da un error: Port error: Could not establish connection. Receiving end does not exist. Probé con comandos AT y el modem responde y en la terminal de uSAGA también sale que el puerto está abierto.

**Comment by edwinspire** [comment]
existe otra tabla llamada outgoing_log, la tabla de mensajes salientes 
se llama outgoing
en ella esta el estado de envio de los sms.

**Comment by Nnino** [comment]
Sale vacia... solamente esta llena la que se llama outgoing

**Comment by Nnino** [comment]
También el status en la tabla outgoing tiene valor 0 para todos los mensajes.

**Comment by edwinspire** [comment]
Crearon un contcacto en el CHIP llamado usms y con su numero telefonico?
Revisar  https://github.com/edwinspire/usms/issues/1

**Comment by Nnino** [comment]
Lo hice, pero no funciona

**Comment by Nnino** [comment]
No reconoce el CHIP, ya que la tabla de Configuraciones/SIM GSM sale vacia

**Comment by edwinspire** [comment]
ok el nombre del contacto debe decir usms o USMS, solo mayusculas o solo 
minisculas. y debe estar en el chip, confirmar que este guardado usando 
comandos at desde minicom

**Comment by Nnino** [comment]
Ya lo revise con los comandos AT y si se encuentra en el chip un contacto llamado usms (lo detecta como USMS con mayúsculas)

**Comment by edwinspire** [comment]
AT+CPBF="usms"

http://m2msupport.net/m2msupport/atcpbf-find-phonebook-entries/

**Comment by Nnino** [comment]
AT+CPBF="USMS"  
+CPBF: 1,"+56994642277",145,"usms"

**Comment by edwinspire** [comment]
Instalar la libreria actualizada
https://github.com/edwinspire/libspire_gsm

**Comment by Nnino** [comment]
Ahora aparece el contacto usms en la tabla, pero aún no se puede enviar SMS.

**Comment by Nnino** [comment]
En el modulo uSAGA la consola del navegador me sigue dando el error "Port error: Could not establish connection. Receiving end does not exist."

**Comment by edwinspire** [comment]
Estan corriendo solo uSAGA o tambien estan corriendo uSMS en otro terminal?
Solo hay que correr uSAGA nada mas.

**Comment by Nnino** [comment]
solamente uSAGA

**Comment by edwinspire** [comment]
Si uSAGA detecta las llamadas significaría que el puerto esta respondiendo.

**Comment by Nnino** [comment]
Claro... el problema es que el navegador es el que me da ese error. Pero efectivamente uSAGA detecta la llamada entrante, el problema está en que no genera los SMS

**Comment by edwinspire** [comment]
detener uSAGA, volver a correr y ver las primeras 20 lineas que aparecen 
en la consola y enviarme.

**Comment by Nnino** [comment]
OK

**Comment by edwinspire** [comment]
El navegador?
si entran en http://localhost:8081/usms_ports_conf.html
pueden ver algo?

**Comment by Nnino** [comment]
run usagad!
uSAGA Software - idowner: 1
Loading devices...
Usar Modem en /dev/ttyUSB0
(IsEnableAndOpen) El Puerto /dev/ttyUSB0 no esta abierto
(IsEnableAndOpen) El Puerto /dev/ttyUSB0 no esta abierto
(IsEnableAndOpen) El Puerto /dev/ttyUSB0 no esta abierto
Run()
(IsEnableAndOpen) El Puerto /dev/ttyUSB0 no esta abierto
open_port:fd=8: Abierto puerto /dev/ttyUSB0
Test Baudrate: 100
Start uHTTP Micro WebServerLicence: LGPL
Contact: edwinspire@gmail.com
Contact: software@edwinspire.com
Contact: http://www.edwinspire.com

Configure
Port: 8081
Root: /home/debian/Escritorio/usms_opensaga_Actual_beta/uSAGA/rootweb
Index: usaga.html

**Comment by Nnino** [comment]
Sí, se ve una tabla con todos los puertos y solamente uno se encuentra enable

**Comment by edwinspire** [comment]
Exactamente cuando hacen que se les presenta el error?

**Comment by edwinspire** [comment]
El error se ve en la consola o en el navegador?
Si es en el navegador cuando estan en que página sucede eso?

**Comment by Nnino** [comment]
El error se ve en la consola... yo uso Google chrome, entonces al inspeccionar elemento sale el error mencionado. Y este error sale en todo el programa, tanto uSAGA como uSMS.

**Comment by edwinspire** [comment]
Están usando la ultima versión que subi el dia de hoy?
La base de datos ha cambiado tambien revisarla.

**Comment by Nnino** [comment]
Si... hace como unas 4 horas que actualicé el sistema a las últimas versiones

**Comment by Nnino** [comment]
E hice los cambios que me mencionaste

**Comment by edwinspire** [comment]
copiar ese error que sale en la consola, con las 5 lineas anteriores y 
posteriores al error y enviarme

**Comment by Nnino** [comment]
Ah disculpa... yo me refería a la consola del navegador.

**Comment by Nnino** [comment]
En la terminal simplemente no dice nada. Sale que detecta la llamada y luego hace nada. Te mandare el log de este suceso de todas formas.

**Comment by Nnino** [comment]
RING

+CLIP: "+56995735953",145,"",128,"",0
Callid = +56995735953
Llamada entrante detectada y almacenda: +56995735953
AT+CMGF=0
OK

*\* (process:16397): WARNING **: libspire_serial.vala:515: [ReadLineWithoutStrip] Timeout to End Line, limit 366.66666666666669 ms

AT+CHUP
OK
AT+CMGF=0
OK
AT+CMGF?
+CMGF: 0

OK
AT+CMGL=4
OK
[/dev/ttyUSB0 EDWINSPIRE_USMS_PROCESS_CTRL_Running]
open_port:fd=6: Abierto puerto /dev/ttyUSB0
AT+CMEE=2
OK
CMS Error Set true
AT+CSQ
+CSQ: 24,0

OK

**Comment by Nnino** [comment]
En la consola del navegador sale este error: 
Port error: Could not establish connection. Receiving end does not exist.         miscellaneous_bindings:235
window on resize to: 361                                                                              usaga_account.js:88

**Comment by edwinspire** [comment]
ok, voy a revisar en la consola del navegador a ver si encuentro lo mismo.

**Comment by edwinspire** [comment]
El window on resize to:XXXX lo uso solo para depuracion, no es una 
falla, es normal.
Pero lo del puerto no lo logro reproducir. La verdad no se a que se debe.
Pueden ver los mapas en openstreetmaps?

**Comment by edwinspire** [comment]
Subi un video hace unos dias en youtube, todo funciona bien.
http://www.usaga-software.edwinspire.com

**Comment by Nnino** [comment]
Sí, los mapas se pueden ver sin problemas.

**Comment by edwinspire** [comment]
Pruebas a realizar:
1) En uSMS > Configuracion > SIM GSM

En el registro correspondiente habilitar la opcion: Other Provider, y 
probar.

Si no funciona probar:

2) En postgres  hay una funcion ejecutar:

SELECT \* FROM fun_outgoing_tosend(idsim);

Donde idsim es la idsim del modem que se está utilizando.
Deberia devolver una fila con 1 mensaje para enviar.

idsim lo pueden ver en la tabla sim.

**Comment by Nnino** [comment]
La primera prueba dio buenos resultados y el sistema envió todos los SMS que ayer no pudo enviar. La otra semana (el martes) seguiré revisando las demás partes del sistema.

Muchas gracias por la ayuda.

**Comment by edwinspire** [comment]
ok.
Seguiré haciendo algunos cambios mas, y cualquier sugerencia es bienvenida.
