### ISSUE TITLE
Error que aparece en el navegador

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#56]
Al seleccionar un Abonado en uSAGA/Abonados/Principal aparece el siguiente error en la consola del navegador:

No existe el item(0) del TagName idgroup en el elemento 1 lib/dojo/jspire/request/Xml.js:26
No existe firstChild del item(0) del TagName note en el elemento 1 lib/dojo/jspire/request/Xml.js:23

Nosotros para el abonado no usamos todos los campos, solamente el nombre y que se encuentre habilitado. Por lo que no sé si tendrá alguna relación el error con ese detalle.

Por cierto, aún persiste el error del Puerto:

Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:235

**Comment by edwinspire** [comment]
No existe el item(0) del TagName idgroup en el elemento 1 
lib/dojo/jspire/request/Xml.js:26
No existe firstChild del item(0) del TagName note en el elemento 1 
lib/dojo/jspire/request/Xml.js:23

So errores "normales" presentados cuando ese campo no es enviado desde 
la base de datos porque es un valor null o vacio, pero no es error como tal.

Port error: Could not establish connection. Receiving end does not 
exist. miscellaneous_bindings:235
No se a que se debe porque no se me presenta ese problema aqui.
