### ISSUE TITLE
Error al modificar un Abonado

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#57]
Al modificar un Abonado en uSAGA/Abonados/Principal, luego de presionar el botón Guardar no se guardan los cambios realizados ni se genera el mensaje que alerta sobre la modificación del Abonado.

**Comment by edwinspire** [comment]
Cuando presionan guardar que muestra en la consola?
Si usan Google Chrome vayan a Herramientas > Consola Javascript
En la parte inferior se habre la consola o sino presionar el boton Console.

Cuando se presiona el Boton guardar de un Abonado sale la siguiente 
linea en la consola del navegador.
1. XHR finished loading: "http://localhost:8081/saveaccount.usaga".

Eso significa que los datos se estan enviando a la base de datos, el 
problema debe estar ahi.

**Comment by Nnino** [comment]
No sale nada. La consola no muestra ningún cambio al presionar el botón Guardar

**Comment by edwinspire** [comment]
Sucede al crear un abonado nuevo y/o con los que ya están creados?

**Comment by Nnino** [comment]
Cuando trato de modificar la información de un abonado que ya se encuentra creado.

**Comment by edwinspire** [comment]
Cuando se carga un Abonado seleccionandolo de la lista, se carga y 
aparece un mensaje con sonido indicando que el abonado se ha cargado.
Sucede asi?

**Comment by edwinspire** [comment]
Pueden probar con otro navegador a ver si se repite el problema.

**Comment by Nnino** [comment]
Sí, es tal como mencionas. Se carga el abonado y aparece el mensaje con sonido.

**Comment by Nnino** [comment]
Ok, probaré con eso más tarde.

**Comment by edwinspire** [comment]
He subido a la rama develop algunos cambios que podrían ayudar a 
localizar el problema.
https://github.com/edwinspire/usaga/tree/develop

**Comment by Nnino** [comment]
En la rama develop sólo se cambió un archivo .sqlite?... Es que nosotros como usamos otro modem, tenemos una configuración que se encuentra en otro archivo .sqlite.

**Comment by edwinspire** [comment]
Estoy subiendo las revisiones a la rama develop y mas tarde uniré los 
cambios a la rama master.

**Comment by edwinspire** [comment]
Logré reproducir el error.
Se presentaba cuando el Abonado no tenía una dirección creada.
Problema era en una función de la base de datos.
Solucionado.
