### ISSUE TITLE
Error al eliminar un teléfono

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#58]
Al tratar de eliminar un teléfono en uSMS/Contactos/Teléfonos no se puede y sale el siguiente mensaje "El numero no puede estar vacio", siendo que ese campo si se encuentra lleno.

**Comment by edwinspire** [comment]
Problema en la funcion de la base de datos. Corrigiendo...

**Comment by edwinspire** [comment]
Solucionado.
Era problemas en una funcion en la base de datos.
Subido a la rama develop.
