### ISSUE TITLE
Duda sobre el Buscar

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#59]
Es posible mover el campo Buscar que está en uSMS/Contactos/Datos, a la posición sobre el campo "Barra de Título" en la que se muestra el listado de Contactos?

**Comment by edwinspire** [comment]
Cual sería la idea de cambiarlo de lugar?
- En los SELECTs que existen en varios lugares uno puede escribir 1 
  letra de lo que está buscando y automáticamente se muestran las opciones 
  que empiezan por esa letra (o letras) eso facilita la busqueda, no es 
  necesario desplegar la lista completa e ir buscando registro por registro.

**Comment by Nnino** [comment]
Ayer estuve revisando y vi que podría tener problemas de usabilidad con este Select. Esto debido que al apretar el botón Buscar y que el select aparezca en esa posición, se sobrecarga visualmente el formulario con campos. Además conceptualmente el formulario representa ingreso de datos, y que un campo de búsqueda se encuentre ahí podría llevar a confusión por parte del usuario no "experto", ya que intentará ingresarle información pensando que es parte de los requisitos del ingreso de datos de un contacto.

La idea que tenía en mente al sugerirte esa ubicación era la del buscador de mensajes de Facebook. Al final puse un link donde se ve una imagen de esta parte en específico.
Entonces, en esta idea el Select se localizaría sobre el listado de los contactos ya ingresados (el que se encuentra más a la izquierda), y al ingresar una letra se van filtrando los resultados que se muestran en el listado de contactos (tal como funcionaba anteriormente). 

Esta una sugerencia, fue hecha porque pensé que quedaría mejor de la forma que te expliqué y porque sería más parecido a programas ya conocidos, lo que facilitaría el entendimiento del usuario.

Respecto a los demás Select, se encuentran bien, y el funcionamiento está perfecto. Era éste en específico el que se podía mejorar.

http://arksoft.com.mx/wp-content/uploads/2012/10/Facebook-mensajes-b%C3%BAsqueda.jpg

**Comment by edwinspire** [comment]
Me parece muy razonable y lógico. Haré el cambio.

**Comment by edwinspire** [comment]
Cambio realizado en la versión develop

**Comment by Nnino** [comment]
Te quedó muy bien, es tal cual como lo había pensado. Tiene un poco de delay al responder pero el resto está perfecto.

**Comment by edwinspire** [comment]
Si, tiene un delay de 1500 ms es para que espere a que se termine de 
escribir para solicitar los datos.
