### ISSUE TITLE
Duda respecto a nuevo componente.

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#60]
Me gustaría saber si es posible que el sistema pueda adaptarse para generar algún tipo de Alarma Sonora con el hardware apropiado, y en caso que así fuera, si conoces qué modelo de Alarma Sonora funcionaría bien o sería compatible con él. 

Te consulto ya que últimamente se nos ha solicitado que el Sistema de Alarma al momento de generar una alarma y enviar los SMS, también debería hacer funcionar una Alarma Sonora que alerte a las personas.

**Comment by edwinspire** [comment]
Si es posible.
Lo mas rapido es utilizar un Modulo GSM de marca DSC, tiene 4 salidas de 
alarma que pueden ser activadas por SMS.
Yo lo he utilizado aca, pero el costo es algo elevado.
Se podria hacer lo mismo por la tercera parte del precio usando un 
microcontrolador o un Ardiuno con un Modem GSM que active uno a varios 
Relés vía sms, es algo más o menos sencillo de hacer.
Por el lado de uSAGA habria que configurar un sms que contenga el 
comando para activar ya sea el Modulo de DSC o uno mandado a hacer.

**Comment by Nnino** [comment]
Me interesaron los relés vía SMS que mencionaste. Conoces alguno que pueda ser activado vía SMS y pueda activar una sirena y una baliza?. En caso de ser así, sabes donde podría conseguirlos?, ya que acá en Chile no encontré.

**Comment by edwinspire** [comment]
Bueno como comenté el Modulo GSM de la marca DSC.
O se pueden mandar a hacer uno.

**Comment by edwinspire** [comment]
En Brasil existe una empresa de alarmas llamada JFL, creo ellos tienen 
un dispositivo que puede hace eso.
Pero más economico sería hacer uno con arduino + modem GSM con las 
salidas de relé que deseen.
