### ISSUE TITLE
Tiempos de espera excesivamente altos

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#62]
Estimado

Hemos estado probando el sistema en un entorno real, con cerca de 200 personas. Pero nos surgió un problema. Resulta que al agregar a las personas como Contactos en uSMS, inicialmente esto se hacía casi automáticamente, pero a medida que ibamos ingresando más personas, más lento se volvía, hasta que luego de ingresar la persona nº 120 o más, ya la espera para ingresar otra persona era de más de 10 seg.

Según lo que se vio a simple vista, es la lista de contactos la que tarda demasiado tiempo en cargar debido a la cantidad de contactos.

Nos gustaría saber si es posible solucionar esto de alguna manera, ya sea no mostrando la lista de contactos y mostrarla solamente si el usuario presiona un botón o de alguna otra forma, para así evitar que el ingreso masivo de personas se vuelva lento y con demasiado tiempo de espera.

Saludos

**Comment by edwinspire** [comment]
Saludos cordiales.
He estado muy ocupado, hace poco he conseguido trabajo tiempo completo y 
por eso he estado un poco desconectado del proyecto. Espero seguir 
aportando mas frecuentemente desde la proxima semana.
Respecto a la pregunta.
Favor enviarme el archivo usms_contacts.html que estan usando 
actualmente para hacer una modificacion que resuelve ese problema.
En la version develop ese problema ya esta resuelto pero hay algunos 
detalles que ajustar en otros lugares pero es igual de funcional.
Pueden descargar la version develop y probar.

La version develop es algo distinta de la master "internamente" de cara 
al usuario es casi lo mismo.
Seguirá habiendo modificaciones principalmente en uSAGA ya que hay 
duplicidad de datos que estoy tratando de evitar.

Cualquier comentario favor hacermelo saber.

**Comment by Nnino** [comment]
Ya estamos probando la versión develop, pero aún no se han hecho pruebas para ver si sucede el mismo problema. Apenas sepamos como funciona te avisaremos.
