### ISSUE TITLE
Duda respecto a buscador de Contactos de uSMS

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#63]
Me gustaría saber que archivo es necesario modificar para que el buscador pueda filtrar Contactos según otros criterios de búsqueda que no sean Nombre y Teléfono. Como por ejemplo mostrar en la lista todos los contactos que tienen un email "X".

**Comment by edwinspire** [comment]
En el filtro de contactos se puede agregar mas criterios de busqueda, 
pero de preferencia campos que solo pertenezcan a la tabla contacts para 
no dificultar tanto la busqueda o para que no muestre registros duplicados.
Actualmente cuando se ingresa un texto a buscar la funcion en postgres 
lo que hace es buscar coincidencias en los campos firstname y lastname. 
Por ejemplo si ingresamos "ac" la funcion buscara y devolvera todos los 
registros que contengan, terminen o empiecen con "ac" en cualquiera de 
los dos campos.

Puedo agregar los campos email 1 y email2 a la tabla mostrada en la 
interfaz web y modificar la funcion 
fun_view_contacts_to_list_search_xml(insearch text DEFAULT ''::text, 
fieldtextasbase64 boolean DEFAULT true) para que haga la busqueda como 
se necesita.

**Comment by Nnino** [comment]
Gracias Edwin, funcionó sin problemas lo mencionado.
