### ISSUE TITLE
No muestra mensaje al modificar un usuario en "Abonados/Usuarios"

### ISSUE THREAD

**Issue by Nnino** [edwinspire/usaga#8]
Al tratar de modificar los datos de un usuario, el sistema no muestra el mensaje "Registro Actualizado" como sucede en "Abonado/Contactos".

**Comment by edwinspire** [comment]
En realidad no es un bug, es solo utilizado para el momento de la depuracion y verificar que todo este saliendo como deberia, por esta ocacion se agragará el alert.
A futuro todas esas notificaciones serás eliminadas. 
Sin embargo si considero necesario informar al usuario que sus acciones fueron exitosas o fallidas, eso se implementara con otro tipo de notificaciones visualmente mas atractivas, esta en proceso de desarollo.

**Comment by Nnino** [comment]
Creo que siempre ha sido buena idea avisar al usuario si es que sus acciones fueron exitosas o no, especialmente al eliminar algún dato, ya que así se previenen eliminaciones accidentales.

**Comment by edwinspire** [comment]
Prevenir al usuario antes de eliminar un registro si es algo necesario por implementar, en la proxima actualizacion estará.
